# Provisioning Configuration
#
# This file is the default configuration for all projects. The fallback order of
# configuration files is:
#
# - project/provisioning/config.local.yaml   (project-specific overrides)
# - project/provisioning/config.yaml         (project-specific defaults)
# - project/provisioning/default.yaml        (global defaults)

# Default project name
#
# Will be used for VirtualBox VM name, unless overridden
name: vagrant-vm

# Domain names to use for Vagrant
#
# The first name will be used as the machine's name,
# subsequent names will be aliased in your hosts file
#
# (When overriding, include vagrant.local if you need it)
hosts:
  - vagrant.local

# Vagrant box to use during provisioning
box: ubuntu/trusty64

# IP address to use on the private network
#
# DHCP is used by default to assign IP addresses dynamically, override only if
# you need a static IP for your box.
#
# Values: "dhcp", or any valid IP
ip: dhcp

# TCP ports to be forwarded
#
# Values: list of { host: port, guest: port }
# (When overriding, include all values)
ports:
  - {host: 8080, guest: 80}

# Virtual machine number of CPUs used (set no higher than number of cores on host)
cpus: 2

# Virtual machine memory (in megabytes)
memory: 512

# Ubuntu release version to use during provisioning
#
# Release version must match the Vagrant box
apt_release: trusty

# Ubuntu mirror to use during provisioning
#
# Packages are loaded from the built-in Ubuntu repositories, which can be slow
# depending on your location. Override this option to use a local mirror
# instead, which is typically faster.
#
# Can be set to Yes to automatically detect the closest mirror, No to use the
# built-in repositories, or a mirror domain as a string.
#
# Values: Yes, No, or any mirror domain name e.g. http://mirror.optus.net/ubuntu/
apt_mirror: Yes

# Puppet provisioning configuration variables
#
# Value must be an object - key/value pairs will be imported into Facter for use by Puppet
# (When overriding, include all values)
puppet:
  app_name: dev
